Senegal gazettes scrapper
CodeForAfrica-SCRAPERS/opengazettes_sn_scrapy pull request #1
Opened 2017-05-23 06:18 UTC by andela-Bgathu

### what does this PR do?
 * Adds opengazettes_sn spider
 * Adds an Item Pipeline

2017-05-23 08:09 UTC, DavidLemayian requested changes

2017-05-23 08:09 UTC, DavidLemayian commented on .gitignore
> -.mypy_cache/
The above items look like they'd be necessary. ☝️

2017-05-23 09:07 UTC, andela-Bgathu commented on .gitignore
> -.mypy_cache/
working to change that

2017-05-23 09:22 UTC, maquchizi requested changes
Please add all files to be ignored to `.gitignore`. This includes `*.pyc` and `*.egg-info/`

2017-05-23 09:22 UTC, maquchizi commented on opengazettes_sn/items.py
> +    gazette_link = scrapy.Field() # link to the gazette on http://www.jo.gouv.sn/spip.php
Avoid inline comments as much as possible. See PEP8 here: https://www.python.org/dev/peps/pep-0008/#inline-comments

2017-05-23 10:12 UTC, andela-Bgathu commented on opengazettes_sn/items.py
> +    gazette_link = scrapy.Field() # link to the gazette on http://www.jo.gouv.sn/spip.php
Sure, this has now been resolved

2017-05-23 10:48 UTC, DavidLemayian approved these changes

2017-05-23 11:32 UTC, maquchizi approved these changes

2017-05-25 16:24 UTC, DavidLemayian commented on opengazettes_sn/settings.py
> +ROBOTSTXT_OBEY = True
@GathuBoswell Could we decide not to? 😁

2017-05-29 18:33 UTC, DavidLemayian approved these changes

2017-05-29 18:33 UTC, merged